import starlight from "@astrojs/starlight";
import sitemap from "@astrojs/sitemap";
import { defineConfig } from "astro/config";
import { readFileSync } from "fs";
import { join } from "path";

// Read manifest for defaults (generated by generate.mjs before astro build)
let manifestData = {};
try {
  manifestData = JSON.parse(
    readFileSync(join(process.cwd(), "public/data/manifest.json"), "utf8")
  );
} catch {
  // Not available yet — use env var defaults
}

const siteTitle =
  process.env.MARKETPLACE_SITE_TITLE ||
  manifestData.marketplaceName ||
  "Plugin Marketplace";

const siteDescription =
  process.env.MARKETPLACE_SITE_DESCRIPTION ||
  manifestData.description ||
  "Browse and discover plugins for your GitHub Copilot CLI marketplace";

const basePath = process.env.MARKETPLACE_BASE_PATH || "/";

// Derive site URL from GitHub Pages convention or env var
const siteUrl =
  process.env.MARKETPLACE_SITE_URL ||
  (process.env.GITHUB_REPOSITORY
    ? `https://${process.env.GITHUB_REPOSITORY_OWNER}.github.io/${process.env.GITHUB_REPOSITORY.split("/")[1]}/`
    : "http://localhost:4321/");

export default defineConfig({
  site: siteUrl,
  base: basePath,
  output: "static",
  integrations: [
    starlight({
      title: siteTitle,
      description: siteDescription,
      social: [],
      customCss: [
        "./src/styles/starlight-overrides.css",
        "./src/styles/global.css",
      ],
      sidebar: [
        {
          label: "Marketplace",
          items: [
            { label: "Home", link: "/" },
            { label: "Plugins", link: "/plugins/" },
          ],
        },
      ],
      disable404Route: true,
      pagefind: true,
      tableOfContents: false,
    }),
    sitemap(),
  ],
  build: {
    assets: "assets",
  },
  trailingSlash: "always",
  vite: {
    build: {
      sourcemap: false,
      chunkSizeWarningLimit: 900,
    },
  },
});
